config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  devise_scope :user do
    get '/login' => 'devise/sessions#new', as: :login
  end

  root 'visitors#index'
  get '/library', to: 'visitors#library', as: :library_page
  
  resources :users, only: [:new, :create]

  resources :participants do
    collection do
      match 'search' => 'participants#search', via: [:get, :post], as: :search
    end
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
	has_many :users 

end

app/models/body.rb
class Body < ActiveRecord::Base
	belongs_to :participant
	
end

app/models/foot.rb
class Foot < ActiveRecord::Base
	belongs_to :participant
	
end

app/models/hand.rb
class Hand < ActiveRecord::Base
	belongs_to :participant
	
end

app/models/participant.rb
class Participant < ActiveRecord::Base

	validates :fname, :presence => true
	validates :lname, :presence => true

	before_save :uppercase_fields

	# def self.to_csv(results)
	# 	CSV.generate do |csv|
	# 		csv << column_names
	# 		results.each do |participant|
	# 			csv << participant.attributes.values_at(*column_names)
	# 		end
	# 	end
	# end

	def uppercase_fields
	  self.fname.capitalize!
	  self.lname.capitalize!
	  self.address.capitalize!
	  self.city.capitalize!
	  self.state.upcase!
	  self.email.downcase!
	  # self.area.capitalize!
	  self.discipline.capitalize!
	end

	def lh_glove_range 
		if self.lh_middle_finger.present?

			left_range = (self.lh_middle_finger * 2.54).round(1)
			
			case left_range
				when 7..7.4   then   left_range = "7–7.4"
				when 7.5..7.8  then  left_range = "7.5–7.8"
				when 7.9..8.2 then   left_range = "7.9–8.2"
				when 8.3..8.6 then   left_range = "8.3–8.6"
				when 8.7..9.0 then   left_range = "8.7–9.0"
				when 9.1..9.2 then   left_range = "9.1–9.2"
				when 9.5..9.8 then   left_range = "9.5–9.8"
				when 9.9..10.3 then  left_range = "9.9–10.3"
			end

			left_range

		end
	end

	def lh_glove_size
		
		if self.lh_middle_finger?
			left_size = (self.lh_middle_finger * 2.54).round(1)

			case left_size
				when 7..7.4   then   left_size = "XXS"
				when 7.5..7.8  then  left_size = "XS"
				when 7.9..8.2 then   left_size = "S"
				when 8.3..8.6 then   left_size = "M"
				when 8.7..9.0 then   left_size = "L"
				when 9.1..9.2 then   left_size = "XL"
				when 9.5..9.8 then   left_size = "XXL"
				when 9.9..10.3 then  left_size = "XXXL"
			end
			self.update(left_glove_size: left_size)
			left_size
		end
	end


	def rh_glove_range 

		if self.rh_middle_finger?
			right_range = (self.rh_middle_finger * 2.54).round(1)
			
			case right_range
				when 7..7.4   then   right_range = "7–7.4"
				when 7.5..7.8  then  right_range = "7.5–7.8"
				when 7.9..8.2 then   right_range = "7.9–8.2"
				when 8.3..8.6 then   right_range = "8.3–8.6"
				when 8.7..9.0 then   right_range = "8.7–9.0"
				when 9.1..9.2 then   right_range = "9.1–9.2"
				when 9.5..9.8 then   right_range = "9.5–9.8"
				when 9.9..10.3 then  right_range = "9.9–10.3"
			end

			right_range
		end
	end

	def rh_glove_size
		if self.rh_middle_finger?
			right_size = self.rh_middle_finger * 2.54
			
			case right_size
				when 7..7.4   then   right_size = "XXS"
				when 7.5..7.8  then  right_size = "XS"
				when 7.9..8.2 then   right_size = "S"
				when 8.3..8.6 then   right_size = "M"
				when 8.7..9.0 then   right_size = "L"
				when 9.1..9.2 then   right_size = "XL"
				when 9.5..9.8 then   right_size = "XXL"
				when 9.9..10.3 then  right_size = "XXXL"
			end
			self.update(right_glove_size: right_size)

			right_size
		end
	end

private

	# def self.ransackable_attributes(auth_object = nil)
	# 	super & %w(fname lname address)
	# end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :admin, :inclusion => {:in => [true, false]}

  has_many :admins


  def is_admin?
  	self.admin == true
  end

  # def active_for_authentication? 
  #   super && approved? 
  # end 

  # def inactive_message 
  #   if !approved? 
  #     :not_approved 
  #   else 
  #     super :approved # Use whatever other message 
  #   end 
  # end

end

app/controllers/application_controller.rb
require 'csv'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_devise_permitted_parameters, if: :devise_controller?

 private
 	def after_sign_out_path_for(resource_or_scope)
 	    login_path
	end

	def configure_devise_permitted_parameters
	    registration_params = [:fname, :lname, :email, :password, :password_confirmation, :admin, :apparel, :footwear, :gloves]

	    if params[:action] == 'update'
	      devise_parameter_sanitizer.for(:account_update) { 
	        |u| u.permit(registration_params << :current_password)
	      }
	    elsif params[:action] == 'create'
	      devise_parameter_sanitizer.for(:sign_up) { 
	        |u| u.permit(registration_params) 
	      }
	    end
	  end

end

app/controllers/participants_controller.rb
class ParticipantsController  < ApplicationController

	before_action :authenticate_user!

	def index
		@people = Participant.all 
		@search = Participant.search(params[:q])
		@participants = @search.result.page(params[:page])
		@search.build_condition
		# if @search.nil?
		# 	respond_to do |format|
	 #      format.html
	 #      format.csv { send_data @people.to_csv, :filename => 'Participant-list.csv' }
	 #    end
  #   end
	end

	def search
		index
		render :index
	end

	def new
		@participant = Participant.new
	end

	def create
		@participant = Participant.new(participant_params)
		if @participant.save
			flash[:notice] = "Entry Saved Successfully."
			redirect_to participant_path(@participant.id)
		else
			render 'new'
		end
	end

	def show
		@xxs = "7–7.4"
		@xs = "7.5–7.8"
		@s = "7.9–8.2"
		@m = "8.3–8.6" 
		@l = "8.7–9.0" 
		@xl = "9.1–9.2" 
		@xxl = "9.5–9.8" 
		@xxxl = "9.9–10.3"

		@participant = Participant.find(params[:id])
	end

	def edit
		@xxs = "7–7.4"
		@xs = "7.5–7.8"
		@s = "7.9–8.2"
		@m = "8.3–8.6" 
		@l = "8.7–9.0" 
		@xl = "9.1–9.2" 
		@xxl = "9.5–9.8" 
		@xxxl = "9.9–10.3"
		
		@participant = Participant.find(params[:id])
	end

	def update
		@participant = Participant.find(params[:id])
		if @participant.update(participant_params)
			flash[:notice] = "Participant Updated Successfully"
			redirect_to participant_path(@participant.id)
		else
			render 'edit'
		end
	end


	def destroy
		@participant = Participant.find(params[:id])
		@participant.destroy
		flash[:notice] = "Participant Successfully Deleted."
		redirect_to new_participant_path
	end

private

	def participant_params
		params.require(:participant).permit(:fname, :lname, :address, :city, :state, :zipcode, :email, :sales_area, :discipline, :participant_type, :age, :gender, :ethnicity, :height_ft, :height_in, :weight, :bra_size, :chest, :natural_waist, :low_hip, :high_hip, :inseam, :thigh, :upper_arm, :sleeve_length, :shoe_size, :lf_width, :lf_heel_to_arch, :lf_heel_to_toe, :rf_width, :rf_heel_to_arch, :rf_heel_to_toe, :lh_palm_width_flat, :lh_palm_width_round, :lh_palm_length, :lh_middle_finger, :rh_palm_width_flat, :rh_palm_width_round, :rh_palm_length, :rh_middle_finger, :tops_size, :alpha_bottoms, :numeric_bottoms, :comments, :phone, :stated_shoe_size, :stated_height_ft, :stated_height_in, :stated_pants_waist, :stated_pants_inseam, :stated_weight, :pant_waist)
	end

end

app/controllers/users_controller.rb
class UsersController  < ApplicationController

	before_action :authenticate_user!

	def index
		
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save 
			flash[:notice] = "New User Created Successfully!"
			redirect_to new_user_path
		else
			render 'new'
		end
	end

private

	def user_params
		params.require(:user).permit(:fname, :lname, :email, :password, :password_confirmation, :admin, :apparel, :footwear, :gloves)
	end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

	before_action :authenticate_user!

	def index
	end

	def library
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	before_action :authenticate_user!

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Innov8</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'styles' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'scripts.js' %>
  <%= csrf_meta_tags %>
  
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
</head>
<body>
	
	<%= yield %>


</body>
</html>

app/views/participants/_apparel.html.erb
<section id="profile-overview">
	<div class="container">
		<div class="row">
			<!-- <div class="alert text-center"><%= notice %></div> -->
			<div class="col-md-3 col-md-offset-1">
				<%= render "gender" %>
			</div>
			<div class="col-md-7">
			<% if notice %>
				<div class="alert alert-success"><%= notice %></div>
			<% end %>
				<h3>Name:</h3>
				<h1><%= @participant.fname + " " + @participant.lname %></h1>
				<h3>Measurements:</h3>
				<div class="row">
					<div class="col-md-3">
						<div style="width: 100%;" class="panel text-center">
							<h1><%= @participant.tops_size %></h1>
							<h5>Tops</h5>
						</div>
					</div>
					<div class="col-md-3">
						<div style="width: 100%;" class="panel text-center">
							<h1><%= @participant.alpha_bottoms %></h1>
							<h5>Alpha Bottoms</h5>
						</div>
					</div>
					<div class="col-md-3">
						<div style="width: 100%;" class="panel text-center">
							<h1><%= @participant.numeric_bottoms %></h1>
							<h5>Num Bottoms</h5>
						</div>
					</div>
					<div class="col-md-3">
						<div style="width: 100%;" class="panel text-center">
							<h1><%= @participant.inseam %></h1>
							<h5>Inseam</h5>
						</div>
					</div>
				</div>
			</div>
		</div> <!-- Profile Overview Row END -->
		<br><br>
	</div>
</section>

app/views/participants/_crud_nav.html.erb
<section id="crud-nav">
	<div class="container">
		<div class="row">
			<div class="col-sm-6">
				<h3 style="margin-left: 23px;"><%= link_to '+ Add Another Entry', new_participant_path %></h3>
			</div>
			<div class="col-sm-6">
				<div class="button-shape pull-right">
					<br>
					<%= link_to 'Edit', edit_participant_path(@participant.id) %>
					<%= link_to 'Delete', participant_path(@participant),
																								:data => {:confirm => "Are you sure you want to delete this entry?",
																								:method => "delete"} %>
				</div>
			</div>			
		</div>	<!-- Crud Nav Links END -->
	</div>
</section>

app/views/participants/_footwear.html.erb
<section id="profile-overview">
	<div class="container">
		<div class="row">
			<!-- <div class="alert text-center"><%= notice %></div> -->
			<div class="col-md-3 col-md-offset-1">
				<%= render "gender" %>
			</div>
			<div class="col-md-7">
			<% if notice %>
				<div class="alert alert-success"><%= notice %></div>
			<% end %>
				<h3>Name:</h3>
				<h1><%= @participant.fname + " " + @participant.lname %></h1>
				<h3>Measurements:</h3>
				<div class="row">
					<div class="col-md-4">
						<div class="panel text-center">
							<h1><%= @participant.stated_shoe_size if @participant.stated_shoe_size? %></h1>
							<h4>Stated Size</h4>
						</div>
					</div>
					<div class="col-md-4">
						<div class="panel text-center">
							<h1>
								<% if @participant.lf_heel_to_toe != @participant.rf_heel_to_toe %>
									<%= @participant.lf_heel_to_toe.to_s + " | " + @participant.rf_heel_to_toe.to_s %>
								<% else %>
									<%= @participant.lf_heel_to_toe %>
								<% end %>
							</h1>
							<h4>Actual Size</h4>
						</div>
					</div>
					<div class="col-md-4">
						<div class="panel text-center">
							<h1>
								<% if @participant.lf_width != @participant.rf_width %>
									<%= @participant.lf_width.to_s + " | " + @participant.rf_width.to_s %>
								<% else %>
									<%= @participant.lf_width %>
								<% end %>
							</h1>
							<h4>Actual Width</h4>
						</div>
					</div>
				</div>
			</div>
		</div> <!-- Profile Overview Row END -->
		<br><br>
	</div>
</section>

app/views/participants/_gender.html.erb
<% if @participant.gender === "Male" %>
	<%= image_tag 'male.png' %>
<% elsif @participant.gender === "Female" %>
	<%= image_tag 'female.png' %>
<% else %>
	<%= image_tag 'furby.png'	%>
<% end %>

app/views/participants/_gloves.html.erb
<section id="profile-overview">
	<div class="container">
		<div class="row">
			<!-- <div class="alert text-center"><%= notice %></div> -->
			<div class="col-md-3 col-md-offset-2">
				<%= render "gender" %>
			</div>
			<div class="col-md-6">
			<% if notice %>
				<div class="alert alert-success"><%= notice %></div>
			<% end %>
				<h3>Name:</h3>
				<h1><%= @participant.fname + " " + @participant.lname %></h1>
				<h3>Measurements:</h3>
				<div class="row">
					<div class="col-md-4">
						<div style="padding-bottom: 5px;" class="panel text-center">
							<h1><%= @participant.lh_middle_finger * 2.54.round(1) if @participant.lh_middle_finger? %></h1>
							<p><%= @participant.lh_glove_range %></p>
							<hr>
							<h1><%= @participant.lh_glove_size %></h1>
							<% if @participant.lh_glove_size === @participant.rh_glove_size %> 
							<h5>Glove Size</h5>
							<% else %>
							<h5>Left Glove</h5>
							<% end %>
						</div>
					</div>
					<% if @participant.lh_glove_size != @participant.rh_glove_size %>
					<div class="col-md-4">
						<div style="padding-bottom: 5px;" class="panel text-center">
							<h1><%= @participant.rh_middle_finger * 2.54.round(1) if @participant.rh_middle_finger? %></h1>
							<p><%= @participant.rh_glove_range %></p>
							<hr>
							<h1><%= @participant.rh_glove_size %></h1>
							<h5>Right Glove</h5>
						</div>
					</div>
					<% end %>
				</div>
			</div>
		</div> <!-- Profile Overview Row END -->
		<br><br>
	</div>
</section>

app/views/participants/_nav.html.erb
<nav>
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-2">
				<%= link_to image_tag('Innov8_Logo_negative.png'), root_path , :alt => 'Innov8 Logo', class: "dashboard-logo" %>
			</div>
			<div class="col-sm-6">
				<ul class="nav nav-pills">
					<li><span class="button button--ujarak"><%= link_to 'New Entry', new_participant_path %></span></li>
					<li><span class="button button--ujarak"><%= link_to 'Find/Edit', participants_path %></span></li>
					<li><span class="button button--ujarak"><%= link_to 'Library', library_page_path %></span></li>
					<% if current_user.admin? %>
					<li><span class="button button--ujarak"><%= link_to 'Admin', new_user_path %></span>
					</li>
					<% end %>
				</ul>
			</div>
			<div class="col-sm-4">
				<div class="nav-user-details pull-right">
					<% if user_signed_in? %>
					  Logged in as, &nbsp;<span style="font-family: 'Open Sans', sans-serif; font-weight: bold;"><%= current_user.fname + " " + current_user.lname %></span>
					  <span class="logout-link"><%= link_to "Logout", destroy_user_session_path, method: :delete %></span>
					<% end %>
				</div>
			</div>
		</div> <!-- Nav Row END -->
	</div> <!-- Container Fluid END -->
</nav>

app/views/participants/_quickview.html.erb
<% if current_user.gloves? %>
	<%= render "gloves" %>
<% elsif current_user.footwear? %>
	<%= render "footwear" %>
<% else %>
	<%= render "apparel" %>
<% end %>

app/views/participants/edit.html.erb
<%= render "nav" %>

<%= render "quickview" %>

<section id="crud-nav">
	<div class="container">
		<div class="row">
			<div class="col-sm-6">
				<h3><%= link_to '← Search ', participants_path %>&nbsp;&nbsp;<% if alert %>
					<div class="alert alert-danger"><%= alert %></div>
				<% end %> | &nbsp;<%= link_to ' + Add Another Entry', new_participant_path %></h3>
			</div>
			<div class="col-sm-6">
				<div class="button-shape pull-right">
					<br>
					<%= link_to 'Delete Entry', participant_path(@participant),
																								:data => {:confirm => "Are you sure you want to delete this entry?",
																								:method => "delete"} %>
				</div>
			</div>			
		</div>	<!-- Crud Nav Links END -->
	</div>
</section>

<section id="form-summary">

<%= render "form" %>
	
</section>

<footer class="page-footer">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="footer mute-grey">
				<p>© 2015 Innov8 Partners, LLC. All rights reserved. Some scary text to prevent unauthorized access or suffer the consequence. dolor sit amet, consectetur adipiscing elit. Ut pretium pretium tempor. Ut eget imperdiet neque.</p>
			</div>
		</div>
	</div>
</footer>

app/views/participants/index.csv.erb
<%- headers = ['First Name', 'Last Name'] -%>
<%= CSV.generate_line headers %>
<%- @participants.each do |participant| -%>
  <%= CSV.generate_line([participant.fname, participant.lname]) %>
<%- end -%>

app/views/participants/index.html.erb
<%= render "nav" %>

<section id="search">
	<div class="container">
		<div class="row">
			<div class="col-xs-8 col-xs-offset-2">
				<div class="text-center">
					<h1>Quick Search</h1>
					<h5 style="opacity: 0.5; font-weight: normal">Set as many conditions as your heart desires. <br>Get back exactly what you need.</h5>
				</div>
				<br>

				<div class="text-center">
					<%= search_form_for @search, url: search_participants_path,
																			 html: { method: :post } do |f| %>
					
							<%= f.condition_fields do |c| %>
						<div class="field">
								<%= c.attribute_fields do |a| %>
									<%= a.attribute_select %>
								<% end %>
								<%= c.predicate_select only: [:cont, :lt, :lteq, :gt, :gteq, :eq, :not_eq], compounds: false %>
								<%= c.value_fields do |v| %>
									<%= v.text_field :value %>
								<% end %>
						</div>
							<% end %>
					
						<%= f.submit "Search", class: "quick-search-btn" %>
						
					<% end %></div>
			</div>	
		</div>
	</div>

	

</section>

<section id="search-results">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<br>
				<%= paginate @participants %>
				<table id="search-results-table" class="table table-hover" cellspacing="0" width="100%">
				    <thead>
				        <tr>
				            <th><%= sort_link @search, :fname, "Name" %></th>
				            <th><%= sort_link @search, :participant_type, "Participant Type" %></th>
				            <th><%= sort_link @search, :city, "City" %></th>
				            <th><%= sort_link @search, :state, "State" %></th>
				            <th><%= sort_link @search, :email, "Email" %></th>
				            <th>Profile</th>
				        </tr>
				    </thead>

				    <% @participants.each do |participant| %>
				    <tbody>
				        <tr>
				            <td><%= participant.fname + " " + participant.lname %></td>
				            <td><%= participant.participant_type %></td>
				            <td><%= participant.city %></td>
				            <td><%= participant.state %></td>
				            <td><%= participant.email %></td>
				            <td><%= link_to 'View Profile', participant_path(participant.id) %></td>
				        </tr>
		        <% end %>
				    </tbody>
				</table>
			</div>
		</div>
		<!-- <div class="pull-right">
			<%= link_to 'Download Entire Participant list', participants_path(:format => :csv) %>
		</div> -->
	</div>
</section>

<footer class="page-footer">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="footer mute-grey">
				<p>© 2015 Innov8 Partners, LLC. All rights reserved. Some scary text to prevent unauthorized access or suffer the consequence. dolor sit amet, consectetur adipiscing elit. Ut pretium pretium tempor. Ut eget imperdiet neque.</p>
			</div>
		</div>
	</div>
</footer>

app/views/participants/new.html.erb
<%= render "nav" %>

<section id="participant-form" class="center-block">

<%= render "form" %>

</section>

<footer class="page-footer">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="footer mute-grey">
				<p>© 2015 Innov8 Partners, LLC. All rights reserved. Some scary text to prevent unauthorized access or suffer the consequence. dolor sit amet, consectetur adipiscing elit. Ut pretium pretium tempor. Ut eget imperdiet neque.</p>
			</div>
		</div>
	</div>
</footer>

app/views/participants/show.html.erb
<%= render "nav" %>

<%= render "quickview" %>

<%= render "crud_nav" %>

<section id="form-summary">

<%= render "form" %>
	
</section>

<footer class="page-footer">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="footer mute-grey">
				<p>© 2015 Innov8 Partners, LLC. All rights reserved. Some scary text to prevent unauthorized access or suffer the consequence. dolor sit amet, consectetur adipiscing elit. Ut pretium pretium tempor. Ut eget imperdiet neque.</p>
			</div>
		</div>
	</div>
</footer>

<script>
	$( "#form-summary :input" ).prop( "disabled", true );
	$( "#form-summary :input" ).text( )
	$( "#form-summary div" ).addClass( "form-group-default-disabled" );
	$( "h3" ).css("padding-top", "10px");
	$( "hr" ).css({"margin-left": "10px", "margin-right": "10px"});

</script>

app/views/visitors/index.html.erb
<nav>
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-2">
				<%= link_to image_tag('Innov8_Logo_negative.png'), root_path , :alt => 'Innov8 Logo', class: "dashboard-logo" %>
			</div>
			<div class="col-sm-6">
				<ul class="nav nav-pills">
					<li><span class="button button--ujarak"><%= link_to 'New Entry', new_participant_path %></span></li>
					<li><span class="button button--ujarak"><%= link_to 'Find/Edit', participants_path %></span></li>
					<li><span class="button button--ujarak"><%= link_to 'Library', library_page_path %></span></li>
					<% if current_user.admin? %>
					<li><span class="button button--ujarak"><%= link_to 'Admin', new_user_path %></span>
					</li>
					<% end %>
				</ul>
			</div>
			<div class="col-sm-4">
				<div class="nav-user-details pull-right">
					<% if user_signed_in? %>
					  Welcome &nbsp;<span style="font-family: 'Open Sans', sans-serif; font-weight: bold;"><%= current_user.fname + " " + current_user.lname %></span>
					  <span class="logout-link"><%= link_to "Logout", destroy_user_session_path, method: :delete %></span>
					<% end %>
				</div>
			</div>
		</div> <!-- Nav Row END -->
	</div> <!-- Container Fluid END -->
</nav>

			

		<section id="dashboard">
			<div class="container">
				<div class="row">
				<% if alert %>
					<div class="alert alert-danger"><%= alert %></div>
				<% end %>
					<div class="col-md-4">
						<div class="panel center-block">
							<figure>
							<%= image_tag 'girl_ICON.png', class: "center-block" %>
								<figcaption class="text-center cl-effect-3">
									<h2><%= link_to 'New Entry', new_participant_path %></h2>
								</figcaption>
							</figure>
						</div>
					</div>
					<div class="col-md-4">
						<div class="panel center-block">
							<figure>
							<%= image_tag 'edit_ICON.png', class: "center-block" %>
								<figcaption class="text-center cl-effect-3">
									<h2><%= link_to 'Find/Edit', participants_path %></h2>
								</figcaption>
							</figure>
						</div>
					</div>
					<div class="col-md-4">
						<div class="panel center-block">
							<figure>
							<%= image_tag 'library_ICON.png', class: "center-block" %>
								<figcaption class="text-center cl-effect-3">
									<h2><%= link_to 'Library', library_page_path %></h2>
								</figcaption>
							</figure>
						</div>
					</div>
				</div>
				<br>
				<br>
				<div class="row">
					<div class="col-md-4 col-md-offset-4">
						<div class="panel panel-coming-soon center-block">
							<figure style="padding: 20px 40px 40px 40px;" class="text-center">
								<h2>More features coming soon...</h2>
							</figure>
						</div>
					</div>
				</div>
			</div> 
		</section>

<footer class="page-footer">
	<div class="row">
		<div class="col-sm-10 col-sm-offset-1">
			<div class="footer mute-grey">
				<p>© 2015 Innov8 Partners, LLC. All rights reserved. Some scary text to prevent unauthorized access or suffer the consequence. dolor sit amet, consectetur adipiscing elit. Ut pretium pretium tempor. Ut eget imperdiet neque.</p>
			</div>
		</div>
	</div>
</footer>

app/views/visitors/library.html.erb
<%= render "participants/nav" %>

<section id="library">
	<div class="container">
		<h3 class="text-center">Documentation coming soon!</h3>
	</div>
</section>